# docs_environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f docs_environment.yml

name: tethys-docs

channels:
- conda-forge

dependencies:
- django =4.2.*
- hunspell-en
- make
- pip
- python
- setuptools_scm
- sphinx
- sphinx-argparse
- sphinxcontrib-spelling
- tethys_dataset_services >=2.0.0
- pip:
  - sphinxawesome-theme
  - sphinx-autobuild
  - sphinx_autodoc_typehints
